### PR TITLE
added Carthage support

### PR DESCRIPTION
**Pull request by oflannabhra**
- Added .xcodeproject to build a SwiftCoAP.framework
- Added Cartfile 
- Changed CocoaAsyncSocket to dependency

Changes will need to be made to the `README.md` to include Carthage instructions

Also, we will need to check releases to make sure they are versioned correctly.

### CODE REVIEW

**Comment by oflannabhra** [comment]
I haven't verified yet if this actually works. These are at least the first steps to making this available through Carthage. Potential changes that will still need to occur: integrating CI so that prebuilt versions can exist

**Comment by oflannabhra** [comment]
@stuffrabbit could you review this?

**Comment by oflannabhra** [comment]
@stuffrabbit any word on whether you can merge this?

**Comment by stuffrabbit** [comment]
Hi, sorry I forgot to answer..
I have no experience in Carthage, and therefore cannot verify your code. Unfortunately, I don't have the time to take care of this for now due to my involvement in other projects. I suggest we keep this feature in your fork for now until you find out that everything works as it is supposed to :)

**Pull request closed without merging**
